#In this file we are saving all output of each stage
from dataclasses import dataclass
class DataIngetionEntity:
    feature_store_file_path : str
    train_file_path : str()

class DataValidationEntity:...
class DataTransformationEntity:...
class ModelTrainerEntity:...
class ModelEvalutionEntity:...
class ModelPusherEntity:...