#In this file we are saving all output of each stage

class DataIngetionEntity:...
class DataValidationEntity:...
class DataTransformationEntity:...
class ModelTrainerEntity:...
class ModelEvalutionEntity:...
class ModelPusherEntity:...