#In this file we are saving all output of each stage
from dataclasses import dataclass
@dataclass
class DataIngestionArtifact:
    feature_store_file_path : str
    train_file_path : str()

class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvalutionArtifact:...
class ModelPusherArtifact:...